### ISSUE TITLE
Corrupt Display

### ISSUE THREAD

**Issue by jbracey2004** [NogginBops/ImGui.NET_OpenTK_Sample#6] opened 2020-05-27 22:38 UTC
When I run the sample, it comes up like this:
![ImGui Sample!_ OpenGL Version_ 3 3 0 - Build 25 20 100 6576 5_27_2020 6_34_55 PM](https://user-images.githubusercontent.com/29154582/83079148-30341d80-a049-11ea-90da-d322972bb1a1.png)
Any idea what's going on here?

**Comment by NogginBops** [comment] 2020-06-02 17:51
Hi, sorry for delayed response.

Can you tell me what OS, .NET version, and GPU you are using?

If you have some more time, would you be able to send a [RenderDoc](https://renderdoc.org) capture so I can look into what I going on?
https://renderdoc.org/docs/how/how_capture_frame.html
After you have the captured frame you can just save the capture to a file and send it to me.

**Comment by jbracey2004** [comment] 2020-06-02 22:15
Here are a couple of snapshots I took

[Snapshots_202006021815.zip](https://github.com/NogginBops/ImGui.NET_OpenTK_Sample/files/4719969/Snapshots_202006021815.zip)

**Comment by NogginBops** [comment] 2020-06-03 02:20
Thanks a lot for the captures!

Just pushed a fix.
If you can test this issue with the latest commit that would be great.

**Comment by jbracey2004** [comment] 2020-06-03 11:11
Hey. Sorry for the late reply.
Thanks for the update version. I tested the new version, and found that the GUI initially displays correctly.
I ran into a new issue. When I mouse over one of the menus, the entire GUI disappears.
I attempted to get the capture via RenderDoc, but I could not get RenderDoc to start the program. Then I fell asleep. I will attempt to get that capture of this occuring later today.

**Comment by NogginBops** [comment] 2020-06-03 19:01
@jbracey2004 I just created a `opengl3.3` branch that actually adhers to the functions available in 3.3 (it used a few 4.5 features). So I think the issue should be solved in that branch. 

Would much appreciate if you could test and see if the issue is fixed. 🙂

**Comment by jbracey2004** [comment] 2020-06-03 20:09
I was able to get the sample on the master branch to work correctly by having the buffers deleted before recreating them when resizing. Below is the corrected code:
```
uint totalVBSize = (uint)(draw_data.TotalVtxCount * Unsafe.SizeOf<ImDrawVert>());
if (totalVBSize > _vertexBufferSize)
{
    int newSize = (int)Math.Max(_vertexBufferSize * 1.5f, totalVBSize);
    GL.DeleteBuffer(_vertexBuffer);
    Util.CreateVertexBuffer("ImGui", out _vertexBuffer);
    GL.NamedBufferData(_vertexBuffer, newSize, IntPtr.Zero, BufferUsageHint.DynamicDraw);
    GL.VertexArrayVertexBuffer(_vertexArray, 0, _vertexBuffer, IntPtr.Zero, Unsafe.SizeOf<ImDrawVert>());
    _vertexBufferSize = newSize;
    Console.WriteLine($"Resized vertex buffer to new size {_vertexBufferSize}");
}
uint totalIBSize = (uint)(draw_data.TotalIdxCount * sizeof(ushort));
if (totalIBSize > _indexBufferSize)
{
    int newSize = (int)Math.Max(_indexBufferSize * 1.5f, totalIBSize);
    GL.DeleteBuffer(_indexBuffer);
    Util.CreateElementBuffer("ImGui", out _indexBuffer);
    GL.NamedBufferData(_indexBuffer, newSize, IntPtr.Zero, BufferUsageHint.DynamicDraw);
    GL.VertexArrayElementBuffer(_vertexArray, _indexBuffer);
    _indexBufferSize = newSize;
    Console.WriteLine($"Resized index buffer to new size {_indexBufferSize}");
}
```
Also note, I also have a [forked version](https://github.com/jbracey2004/ImGui.NET_OpenTK_Sample) that uses the old-fashioned glBuffer calls instead of the glNamedBuffer calls. It seems to be able to resize buffers without having to delete and recreate them.

Also, I have tested the app on the opengl3.3 branch. That one works too.

**Closed** 2020-06-04 05:40 UTC

**Comment by NogginBops** [comment] 2020-06-04 19:32
@jbracey2004 I thought I would let you know that I just discovered a problem with the projection matrix that is used, and it's making the text blurry.
When creating the projection matrix the call should look like this:
```cs
Matrix4 mvp = Matrix4.CreateOrthographicOffCenter(
                0.0f,
                io.DisplaySize.X,
                io.DisplaySize.Y,
                0.0f,
                -1.0f,
                1.0f);
```
The change is that the first argument is changed from `-1.0` to `0.0`.
